### ISSUE TITLE
Request for CI & Benching

### ISSUE THREAD

**Issue by Skarlett** [BourgondAries/fast-logger#1]
Seeing as the name is "fast-logger', It would be nice to see a comparison between some libraries and yours as far as bench times go. To keep this consistent, it should be updated before each commit, or having a bot do it for you (like Travis-CI).

**Comment by kstrafe** [comment]
Hello @Skarlett, unfortunately I have too many repositories last time I checked with travis so I'm unable to use its services for CI. There are benchmarks you can run, but it would indeed be better to have this in a document somewhere.

**Comment by kstrafe** [comment]
This seems to be resolved!
