### ISSUE TITLE
Release for stable Rust

### ISSUE THREAD

**Issue by agodnic** [BourgondAries/fast-logger#2]
Hi!

Are you considering a release on stable Rust?

If so, what things need to be changed?

**Comment by kstrafe** [comment]
Hello! The only thing that's needed is to remove the `extern crate test` part which relies on an unstable feature. This is mainly used for benchmarking, and could be replaced by criterion or maybe a compile flag.

**Comment by kstrafe** [comment]
@unterkontrolle v0.6.0 is now usable on stable.
